---
- name: Install k3s on single-node cluster
  hosts: k3s_node
  become: true
  tasks:
    - name: Install curl
      apt:
        name: curl
        state: present
        update_cache: true

    - name: Install latest k3s
      shell: curl -sfL https://get.k3s.io | sh -

    - name: Wait for k3s service
      wait_for:
        port: 6443
        timeout: 60

    - name: Copy kubeconfig to user's home
      shell: cp /etc/rancher/k3s/k3s.yaml /home/ubuntu/.kube/config && chown ubuntu:ubuntu /home/ubuntu/.kube/config
      when: ansible_env.USER == "ubuntu"

